<?php
	echo "Got to submit page.";
	echo "<br />";
	$editWhichMember = $_POST['whichMember'];
	$email = $_POST['email'];
	$firstName = $_POST['firstName'];
	$middle = $_POST['middle'];	
	$lastName = $_POST['lastName'];
	$salutation = $_POST['salutation'];
	$title = $_POST['title'];
	$company = $_POST['company'];
	$officePhone = $_POST['officePhone'];
	$billingAddress1 = $_POST['billingAddress1'];
	$billingAddress2 = $_POST['billingAddress2'];
	$nickname = $_POST['nickname'];
	$city = $_POST['city'];
	$state = $_POST['state'];
	$zip = $_POST['zip'];
	$ass = $_POST['ass'];
	$assPhone = $_POST['assPhone'];
	$assEmail = $_POST['assEmail'];
	$deptSize = $_POST['deptSize'];
	$territory = $_POST['territory'];
	$joinDate = $_POST['joinDate'];
	$membersCode = $_POST['membersCode'];
	$industry = $_POST['industry'];
	$remarks = $_POST['remarks'];
	$recruitedBy = $_POST['recruitedBy'];
	$mobilePhone = $_POST['mobilePhone'];
	$fax = $_POST['fax'];
	$home = $_POST['home'];
	$role = $_POST['role'];
	$additionalEmail = $_POST['additionalEmail'];
	$contactType = $_POST['contactType'];
	$source = $_POST['source'];
	$chapter = $_POST['chapter'];
	$joinDate = $_POST['joinDate'];
	$groups = $_POST['groups'];
	$whichQuery = 'updateMember';
	require('queries.php');
?>